### ISSUE TITLE
RuntimeError: prim::TupleUnpack not matched to tuple construct

### ISSUE THREAD

**Issue by zhaolanhuang** [zhaolanhuang/U-TOE#6]
(from mail communication with u-toe user)

When I pass the torchscript model to TVM, I met with the following problem.
It may because of the function torch.jit.script

Here is the error:

```
/path-to-python/python3.10/site-packages/torch/ao/quantization/utils.py:310: UserWarning: must run observer before calling calculate_qparams. Returning default values.
  warnings.warn(
[W lower_tuples.cpp:253] Warning: tuple appears in the op outputs, but this op does not forward tuples, unsupported kind: prim::GetAttr (function flattenOutputs)
Traceback (most recent call last):
  File "/path-to-project/testTuple.py", line 61, in <module>
    main()
  File "/path-to-project/testTuple.py", line 40, in main
    model = tvmc.load('./script_tuple.pth', shape_dict=shape_dict)
  File "/path-to-tvm/tvm/python/tvm/driver/tvmc/frontends.py", line 476, in load_model
    mod, params = frontend.load(path, shape_dict, **kwargs)
  File "/path-to-tvm/tvm/python/tvm/driver/tvmc/frontends.py", line 260, in load
    return relay.frontend.from_pytorch(
  File "/path-to-tvm/tvm/python/tvm/relay/frontend/pytorch.py", line 4962, in from_pytorch
    _run_jit_passes(graph, enable_lower_all_tuples)
  File "/path-to-tvm/tvm/python/tvm/relay/frontend/pytorch.py", line 4459, in _run_jit_passes
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: prim::TupleUnpack not matched to tuple construct
```

**Comment by Sliverk** [comment]
It is not a problem appears in the project.
I have found out that if we use jit.trace not jit.script, everything will be ok.
But I am still curious why jit.script does not work.
Here is the test code

```python
import torch
import torch.nn as nn
from torch.quantization import prepare_qat, get_default_qat_qconfig, convert
import torch.nn.functional as F

import tvm
from tvm import relay
from tvm.relay.backend import Executor
from tvm.relay.backend import Runtime
from tvm.driver import tvmc
from tvm.micro import export_model_library_format

class A(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 16, 1, 1, 0, bias=False)
        self.conv2 = nn.Conv2d(16, 32, 1, 1, 0, bias=False)
        self.conv3 = nn.Conv2d(32, 64, 1, 1, 0, bias=False)
    
    def forward(self, x):
        x1 = self.conv1(x)
        x2 = self.conv2(x1)
        x3 = self.conv3(x2)

        return x3
        # return torch.cat((x1, x2, x3), 1)

def main():
    model = A()
    model.qconfig = get_default_qat_qconfig('qnnpack')
    model = prepare_qat(model, inplace=True)
    model_fp32 = model
    model_fp32.eval()
    model_int8 = convert(model_fp32, inplace=True)    
    scripted_model = torch.jit.script(model_int8)
    torch.jit.save(scripted_model, f'./script_tuple.pth')

    # Step 1: Load Model
    shape_dict = {'input0': [1,3, 224, 224]}
    model = tvmc.load('./script_tuple.pth', shape_dict=shape_dict)
    # model = tvmc.load('weights/mnist_0.983_quantized.tflite')

    # tvmc.tune(model, target='llvm')

    RUNTIME = Runtime('crt', {'system-lib':False})
    EXECUTOR = Executor('aot',
        {"unpacked-api": True, 
        "interface-api": "c", 
        "workspace-byte-alignment": 4,
        "link-params": True,},
        )

    TARGET = tvm.target.target.stm32('stm32F7xx')

    with tvm.transform.PassContext(opt_level=3, config={
                                                        "tir.disable_vectorize": True, 
                                                        "tir.usmp.enable": True
                                                        }): # what is usmp? -> Enable Unified Static Memory Planning
        module = relay.build(model.mod, target=TARGET, runtime=RUNTIME, params=model.params, executor=EXECUTOR)

if __name__ == '__main__':
    main()
```

**Comment by zhaolanhuang** [comment]
hmm maybe the anwser can be found here : [TorchScript: Tracing vs. Scripting](https://ppwwyyxx.com/blog/2022/TorchScript-Tracing-vs-Scripting/)

And seems that trace is better than script, quote:
`Why tracing is better? TL;DR: (i) it will not damage the code quality; (ii) its main limitations can be addressed by mixing with scripting.`
